[Xorg_dri2proto]
git-tree-sha1 = "cda2bc9804973fbb1476007c0f183709ae643cea"

    [[Xorg_dri2proto.download]]
    sha256 = "6c9b269a43d5274ffb61fbbf21f9bc8f007e513dfbcf698dda1eae71a3972775"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_dri2proto_jll.jl/releases/download/Xorg_dri2proto-v2.8.0+1/Xorg_dri2proto.v2.8.0.any.tar.gz"
